name: .NET Core Desktop

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalacja .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.0  # Wersja .NET SDK

      # Przywrócenie zależności
      - name: Restore dependencies
        run: dotnet restore

      # Budowanie projektu
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Uruchamianie testów
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Sprawdzanie formatowania kodu (opcjonalne)
      - name: Check code formatting with dotnet-format
        run: dotnet format --check
